services:
  frontend:
    build:
      context: .
      target: runner
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
    command: node server.js
