version: '3.9'

services:
  ruqya-frontend:
    image: ruqya-frontend:1.1.0
    build:
      context: ../frontend
#      platforms:
#        - linux/amd64
#        - linux/arm64
    ports:
      - "3001:3000"
    depends_on:
      - ruqya-api
    env_file:
      - ../frontend/.env.production
    networks:
      - app-network

  ruqya-admin:
    image: ruqya-admin:1.1.0
    build:
      context: ../admin-panel
#      platforms:
#        - linux/amd64
#        - linux/arm64
    ports:
      - "3002:3000"
    depends_on:
      - ruqya-api
    env_file:
      - ../admin-panel/.env.production
    networks:
      - app-network

  ruqya-api:
    image: ruqya-api:1.1.0
    build:
      context: ../api-service
#      platforms:
#        - linux/amd64
#        - linux/arm64
    ports:
      - "5050:5050"
    env_file:
      - ../api-service/.env.production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
