version: '3.8'

services:
  ruqya-frontend:
    build: ../frontend
    ports:
      - "3001:3000"
    depends_on:
      - ruqya-api
    env_file:
      - ../frontend/.env.production
    networks:
      - app-network

  ruqya-admin:
    build: ../admin-panel
    ports:
      - "3002:3000"
    depends_on:
      - ruqya-api
    env_file:
      - ../admin-panel/.env.production
    networks:
      - app-network

  ruqya-api:
    build: ../api-service
    ports:
      - "5050:5050"
    env_file:
      - ../api-service/.env.production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


